jenkins file de imen

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -20,27 +20,27 @@ pipeline {
              steps {
                  script {
                      dir('my-terraform-project/remote_backend') {
-                         sh  "terraform init"
+                         sh "terraform init"
                          // Apply Terraform configuration
-                         sh  "terraform apply --auto-approve"
+                         sh "terraform apply --auto-approve"
                      }
                      dir('my-terraform-project') {
                          // Initialize Terraform
-                         sh  "terraform init"
-                         sh  "terraform plan -lock=false"
+                         sh "terraform init"
+                         sh "terraform plan -lock=false"
 
                          // Apply Terraform configuration
-                         sh  "terraform apply -lock=false --auto-approve"
+                         sh "terraform apply -lock=false --auto-approve"
 
                          // Get EC2 Public IP
-                         EC2_PUBLIC_IP = sh (
+                         EC2_PUBLIC_IP = sh(
                              script: 'terraform output instance_details | grep "instance_public_ip" | awk \'{print $3}\' | tr -d \'"\'',
                              returnStdout: true
                          ).trim()
 
                          // Get RDS Endpoint
                          // Get RDS Endpoint
-                         RDS_ENDPOINT = sh (
+                         RDS_ENDPOINT = sh(
                              script: '''
                              terraform output rds_endpoint | grep "endpoint" | awk -F'=' '{print $2}' | tr -d '[:space:]"' | sed 's/:3306//'
                              ''',
@@ -48,7 +48,7 @@ pipeline {
                          ).trim()
 
 
-                        DEPLOYER_KEY_URI = sh (
+                        DEPLOYER_KEY_URI = sh(
                              script: 'terraform output deployer_key_s3_uri | tr -d \'"\'',
                              returnStdout: true
                          ).trim()
@@ -205,84 +205,121 @@ pipeline {
                 }
             }
         }
-        stage('Check and Manage Ansible Container') {
+
+ //for linux users
+
+        stage('Check Ansible Version') {
             steps {
                 script {
-                    dir('ansible') {
-                        sh '''
-                        echo "Checking and managing the 'my_ansible_container'"
-
-                        CONTAINER_NAME="my_ansible_container"
-                        IMAGE_NAME="cytopia/ansible"
-
-                        # Stop and remove the container if it exists
-                        if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
-                            echo "Container ${CONTAINER_NAME} exists. Stopping and removing it..."
-                            docker stop ${CONTAINER_NAME} || true
-                            docker rm ${CONTAINER_NAME} || true
-                        fi
-
-                        # Create and start a new container with volume mounted
-                        echo "Creating and starting a new container with the ansible directory mounted..."
-                        docker run -dit --name ${CONTAINER_NAME} \
-                            -v $(pwd):/ansible \
-                            -w /ansible \
-                            ${IMAGE_NAME} \
-                            sh -c 'while true; do sleep 30; done'
-
-                        # Verify the ansible directory and its contents in the container
-                        echo "Verifying the ansible directory and its contents in the container:"
-                        docker exec ${CONTAINER_NAME} sh -c "ls /ansible && cat /ansible/hosts || echo 'Directory or file not found'"
-                        '''
-                    }
+                    sh """
+                    echo "Printing the current Ansible version:"
+                    ansible --version
+                    """
                 }
             }
         }
-        stage('Install OpenSSH in Ansible Container') {
-                    steps {
-                        script {
-                            dir('ansible') {
-                                sh '''
-                                echo "Installing OpenSSH in the Ansible container"
-
-                                CONTAINER_NAME="my_ansible_container"
-
-                                # Install OpenSSH
-                                docker exec ${CONTAINER_NAME} sh -c "apk update && apk add openssh"
-
-                                # Verify OpenSSH installation
-                                echo "Verifying OpenSSH installation"
-                                docker exec ${CONTAINER_NAME} ssh -V || echo "OpenSSH not installed correctly"
-                                '''
-                            }
-                        }
-                    }
-                }
-
         stage('Run Ansible Playbook') {
             steps {
                 script {
                     dir('ansible') {
-                        sh '''
-                        echo "Running Ansible playbook inside the container"
+                        sh """
+                        if [ -f "docker_deploy_playbook.yml" ]; then
+                            echo "Found playbook docker_deploy_playbook.yml"
 
-                        CONTAINER_NAME="my_ansible_container"
-                        PLAYBOOK="docker_deploy_playbook.yml"
-                        INVENTORY="hosts"
-
-                        # Check if playbook exists
-                        if [ -f "${PLAYBOOK}" ]; then
-                            echo "Playbook ${PLAYBOOK} found. Running it now..."
-                            docker exec ${CONTAINER_NAME} ansible-playbook -i ${INVENTORY} ${PLAYBOOK}
+                            # Run the Ansible playbook
+                            ansible-playbook -i hosts docker_deploy_playbook.yml
                         else
-                            echo "Playbook ${PLAYBOOK} not found!"
+                            echo "Playbook docker_deploy_playbook.yml not found!"
                             exit 1
                         fi
-                        '''
+                        """
                     }
                 }
             }
         }
+
+
+//  for windows users
+
+
+    //     stage('Check and Manage Ansible Container') {
+    //         steps {
+    //             script {
+    //                 dir('ansible') {
+    //                     sh '''
+    //                     echo "Checking and managing the 'my_ansible_container'"
+
+    //                     CONTAINER_NAME="my_ansible_container"
+    //                     IMAGE_NAME="cytopia/ansible"
+
+    //                     # Stop and remove the container if it exists
+    //                     if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
+    //                         echo "Container ${CONTAINER_NAME} exists. Stopping and removing it..."
+    //                         docker stop ${CONTAINER_NAME} || true
+    //                         docker rm ${CONTAINER_NAME} || true
+    //                     fi
+
+    //                     # Create and start a new container with volume mounted
+    //                     echo "Creating and starting a new container with the ansible directory mounted..."
+    //                     docker run -dit --name ${CONTAINER_NAME} \
+    //                         -v $(pwd):/ansible \
+    //                         -w /ansible \
+    //                         ${IMAGE_NAME} \
+    //                         sh -c 'while true; do sleep 30; done'
+
+    //                     # Verify the ansible directory and its contents in the container
+    //                     echo "Verifying the ansible directory and its contents in the container:"
+    //                     docker exec ${CONTAINER_NAME} sh -c "ls /ansible && cat /ansible/hosts || echo 'Directory or file not found'"
+    //                     '''
+    //                 }
+    //             }
+    //         }
+    //     }
+    //     stage('Install OpenSSH in Ansible Container') {
+    //                 steps {
+    //                     script {
+    //                         dir('ansible') {
+    //                             sh '''
+    //                             echo "Installing OpenSSH in the Ansible container"
+
+    //                             CONTAINER_NAME="my_ansible_container"
+
+    //                             # Install OpenSSH
+    //                             docker exec ${CONTAINER_NAME} sh -c "apk update && apk add openssh"
+
+    //                             # Verify OpenSSH installation
+    //                             echo "Verifying OpenSSH installation"
+    //                             docker exec ${CONTAINER_NAME} ssh -V || echo "OpenSSH not installed correctly"
+    //                             '''
+    //                         }
+    //                     }
+    //                 }
+    //             }
+
+    //     stage('Run Ansible Playbook') {
+    //         steps {
+    //             script {
+    //                 dir('ansible') {
+    //                     sh '''
+    //                     echo "Running Ansible playbook inside the container"
+
+    //                     CONTAINER_NAME="my_ansible_container"
+    //                     PLAYBOOK="docker_deploy_playbook.yml"
+    //                     INVENTORY="hosts"
+
+    //                     # Check if playbook exists
+    //                     if [ -f "${PLAYBOOK}" ]; then
+    //                         echo "Playbook ${PLAYBOOK} found. Running it now..."
+    //                         docker exec ${CONTAINER_NAME} ansible-playbook -i ${INVENTORY} ${PLAYBOOK}
+    //                     else
+    //                         echo "Playbook ${PLAYBOOK} not found!"
+    //                         exit 1
+    //                     fi
+    //                     '''
+    //                 }
+    //             }
+    //         }
+    //     }
 
     }
     post {
@@ -297,5 +334,3 @@ pipeline {
             }
         }
 }
-
-
