test jenkins file

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -8,12 +8,11 @@ pipeline {
             AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
             AWS_CREDENTIALS_ID = 'aws-credentials'
             ECR_REPO_URL = '307946682088.dkr.ecr.us-east-1.amazonaws.com'
-            ECR_REPO_NAME = 'test'
+            ECR_REPO_NAME = 'enis-app'
             IMAGE_REPO = "${ECR_REPO_URL}/${ECR_REPO_NAME}"
             IMAGE_REPO_FRONTEND = "${IMAGE_REPO}:frontend-app-1.0"
             IMAGE_REPO_BACKEND = "${IMAGE_REPO}:backend-app-1.0"
             AWS_REGION = "us-east-1"
-
         }
     stages {
          stage('Provision Server and Database') {
@@ -206,7 +205,7 @@ pipeline {
             }
         }
 
- //for linux users
+//  for linux users
 
         stage('Check Ansible Version') {
             steps {
@@ -242,84 +241,84 @@ pipeline {
 //  for windows users
 
 
-    //     stage('Check and Manage Ansible Container') {
-    //         steps {
-    //             script {
-    //                 dir('ansible') {
-    //                     sh '''
-    //                     echo "Checking and managing the 'my_ansible_container'"
+//         stage('Check and Manage Ansible Container') {
+//             steps {
+//                 script {
+//                     dir('ansible') {
+//                         sh '''
+//                         echo "Checking and managing the 'my_ansible_container'"
 
-    //                     CONTAINER_NAME="my_ansible_container"
-    //                     IMAGE_NAME="cytopia/ansible"
+//                         CONTAINER_NAME="my_ansible_container"
+//                         IMAGE_NAME="cytopia/ansible"
 
-    //                     # Stop and remove the container if it exists
-    //                     if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
-    //                         echo "Container ${CONTAINER_NAME} exists. Stopping and removing it..."
-    //                         docker stop ${CONTAINER_NAME} || true
-    //                         docker rm ${CONTAINER_NAME} || true
-    //                     fi
+//                         # Stop and remove the container if it exists
+//                         if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
+//                             echo "Container ${CONTAINER_NAME} exists. Stopping and removing it..."
+//                             docker stop ${CONTAINER_NAME} || true
+//                             docker rm ${CONTAINER_NAME} || true
+//                         fi
 
-    //                     # Create and start a new container with volume mounted
-    //                     echo "Creating and starting a new container with the ansible directory mounted..."
-    //                     docker run -dit --name ${CONTAINER_NAME} \
-    //                         -v $(pwd):/ansible \
-    //                         -w /ansible \
-    //                         ${IMAGE_NAME} \
-    //                         sh -c 'while true; do sleep 30; done'
+//                         # Create and start a new container with volume mounted
+//                         echo "Creating and starting a new container with the ansible directory mounted..."
+//                         docker run -dit --name ${CONTAINER_NAME} \
+//                             -v $(pwd):/ansible \
+//                             -w /ansible \
+//                             ${IMAGE_NAME} \
+//                             sh -c 'while true; do sleep 30; done'
 
-    //                     # Verify the ansible directory and its contents in the container
-    //                     echo "Verifying the ansible directory and its contents in the container:"
-    //                     docker exec ${CONTAINER_NAME} sh -c "ls /ansible && cat /ansible/hosts || echo 'Directory or file not found'"
-    //                     '''
-    //                 }
-    //             }
-    //         }
-    //     }
-    //     stage('Install OpenSSH in Ansible Container') {
-    //                 steps {
-    //                     script {
-    //                         dir('ansible') {
-    //                             sh '''
-    //                             echo "Installing OpenSSH in the Ansible container"
+//                         # Verify the ansible directory and its contents in the container
+//                         echo "Verifying the ansible directory and its contents in the container:"
+//                         docker exec ${CONTAINER_NAME} sh -c "ls /ansible && cat /ansible/hosts || echo 'Directory or file not found'"
+//                         '''
+//                     }
+//                 }
+//             }
+//         }
+//         stage('Install OpenSSH in Ansible Container') {
+//                     steps {
+//                         script {
+//                             dir('ansible') {
+//                                 sh '''
+//                                 echo "Installing OpenSSH in the Ansible container"
 
-    //                             CONTAINER_NAME="my_ansible_container"
+//                                 CONTAINER_NAME="my_ansible_container"
 
-    //                             # Install OpenSSH
-    //                             docker exec ${CONTAINER_NAME} sh -c "apk update && apk add openssh"
+//                                 # Install OpenSSH
+//                                 docker exec ${CONTAINER_NAME} sh -c "apk update && apk add openssh"
 
-    //                             # Verify OpenSSH installation
-    //                             echo "Verifying OpenSSH installation"
-    //                             docker exec ${CONTAINER_NAME} ssh -V || echo "OpenSSH not installed correctly"
-    //                             '''
-    //                         }
-    //                     }
-    //                 }
-    //             }
+//                                 # Verify OpenSSH installation
+//                                 echo "Verifying OpenSSH installation"
+//                                 docker exec ${CONTAINER_NAME} ssh -V || echo "OpenSSH not installed correctly"
+//                                 '''
+//                             }
+//                         }
+//                     }
+//                 }
 
-    //     stage('Run Ansible Playbook') {
-    //         steps {
-    //             script {
-    //                 dir('ansible') {
-    //                     sh '''
-    //                     echo "Running Ansible playbook inside the container"
+//         stage('Run Ansible Playbook') {
+//             steps {
+//                 script {
+//                     dir('ansible') {
+//                         sh '''
+//                         echo "Running Ansible playbook inside the container"
 
-    //                     CONTAINER_NAME="my_ansible_container"
-    //                     PLAYBOOK="docker_deploy_playbook.yml"
-    //                     INVENTORY="hosts"
+//                         CONTAINER_NAME="my_ansible_container"
+//                         PLAYBOOK="docker_deploy_playbook.yml"
+//                         INVENTORY="hosts"
 
-    //                     # Check if playbook exists
-    //                     if [ -f "${PLAYBOOK}" ]; then
-    //                         echo "Playbook ${PLAYBOOK} found. Running it now..."
-    //                         docker exec ${CONTAINER_NAME} ansible-playbook -i ${INVENTORY} ${PLAYBOOK}
-    //                     else
-    //                         echo "Playbook ${PLAYBOOK} not found!"
-    //                         exit 1
-    //                     fi
-    //                     '''
-    //                 }
-    //             }
-    //         }
-    //     }
+//                         # Check if playbook exists
+//                         if [ -f "${PLAYBOOK}" ]; then
+//                             echo "Playbook ${PLAYBOOK} found. Running it now..."
+//                             docker exec ${CONTAINER_NAME} ansible-playbook -i ${INVENTORY} ${PLAYBOOK}
+//                         else
+//                             echo "Playbook ${PLAYBOOK} not found!"
+//                             exit 1
+//                         fi
+//                         '''
+//                     }
+//                 }
+//             }
+//         }
 
     }
     post {
