update jenkinsfile and terraform main

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -168,6 +168,27 @@ pipeline {
                 }
             }
         }
+        stage('Update Hosts File') {
+            steps {
+                script {
+                    dir('ansible') {
+                        // Update the second line with the EC2_PUBLIC_IP variable
+                        sh """
+                        if [ -f "hosts" ]; then
+                            echo "Found hosts file at $(pwd)"
+                            sed -i "2s|.*|${EC2_PUBLIC_IP}|" hosts
+                            echo "Updated hosts file:"
+                            cat hosts
+                        else
+                            echo "hosts file not found in $(pwd)!"
+                            exit 1
+                        fi
+                        """
+                    }
+                }
+            }
+        }
+
 
 
     }
